# Generated by Django 4.0.3 on 2022-03-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_scope', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ScopesArtical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art', to='articles.article')),
                ('scopes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.scopes')),
            ],
        ),
        migrations.AddField(
            model_name='scopes',
            name='articals',
            field=models.ManyToManyField(related_name='scope', through='articles.ScopesArtical', to='articles.article'),
        ),
    ]
